version: '3'

services:
    elastalert:
        image: docker.io/kuzoncby/elastalert:0.2.1
        build: 
            context: .
        environment:
        - ELASTICSEARCH_HOST=elasticsearch # <1>
        - ELASTICSEARCH_PORT=9200
        
        