= Elastalert Docker Image

Docker image with Elastalert on CentOS 7.

link:README-zh.adoc[简体中文]

== Volumes

- /opt/logs       - Elastalert logs will be written to this directory.
- /opt/config     - Elastalert (elastalert_config.yaml) and the configuration file for mail server authentication.
- /opt/rules      - Contains Elastalert rules.

== Build Image

[source,bash]
----
docker-compose build --no-cache
----

== Run Elastalert

Clone this project and modify Elastalert configuration file:

.config/elastalert_config.yaml
[source,yaml]
----
include::config/elastalert_config.yaml[Elastalert Config]
----
<1> SMTP server
<2> SMTP port
<3> Mail address
<4> Authentication configuration

Modify authentication configuration:

.config/auth.txt
[source,ini]
----
include::config/auth.txt[Auth Config]
----

Set up alarm rules, using Heartbeat as an example:

.Heartbeat
[plantuml,diagram-heartbeat,svg]
----
include::heartbeat.puml[Heartbeat]
----

First, monitor the required devices through Heartbeat, and Heartbeat will transfer the data of these devices to the ES for storage. To learn more about Heartbeat please refer: link:https://www.elastic.co/guide/en/beats/heartbeat/current/configuring-howto-heartbeat.html[]

Elastalert regularly checks for faulty services in Heartbeat and sends emails to administrators. All services are normal and will not be sent.

.rules/heartbeat-demo.yaml
[source,yaml]
----
include::rules/heartbeat-demo.yaml[Rule]
----
<1> Checks for faulty services in Heartbeat


After all settings are completed, perform the following operations to start:

.bash
[source,bash]
----
docker-compose up -d
----
